import EmergencyPhotoApproval from '../../components/EmergencyPhotoApproval'
import { useEffect, useMemo, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { useAuth } from '../../contexts/AuthContext'
import { supabase } from '../../lib/supabase'
import { ALLOWED_TRANSITIONS, assignRequest, changeRequestStatus, getAllRequests, getNotifications, getOliWorkers, getRequestDetails, markNotificationRead, publishCollectionPoint, REQUEST_TYPES, subscribeToNotifications } from '../../services/request.service'

const relations={EMERGENCIA:'solicitud_emergencia',KIT:'solicitud_kit',OFERTA_RECURSO:'oferta_recursos',ALIADO:'solicitud_aliado',VOLUNTARIO:'solicitud_voluntario',PUNTO_ACOPIO:'solicitud_punto_acopio'}
const labels=Object.fromEntries(REQUEST_TYPES)
const statusColor={RECIBIDA:'bg-blue-100 text-blue-800',EN_REVISION:'bg-amber-100 text-amber-800',OBSERVADA:'bg-orange-100 text-orange-800',APROBADA:'bg-emerald-100 text-emerald-800',ATENDIDA:'bg-teal-100 text-teal-800',RECHAZADA:'bg-red-100 text-red-800',CERRADA:'bg-slate-200 text-slate-700',CANCELADA:'bg-slate-200 text-slate-700'}
const statusLabels={RECIBIDA:'Recibida',EN_REVISION:'En revisión',OBSERVADA:'Requiere información',APROBADA:'Aprobada',ATENDIDA:'Atendida',RECHAZADA:'Rechazada',CERRADA:'Cerrada',CANCELADA:'Cancelada'}

function Dashboard(){
 const {profile}=useAuth(), navigate=useNavigate()
 const [requests,setRequests]=useState([]),[workers,setWorkers]=useState([]),[selected,setSelected]=useState(null)
 const [notifications,setNotifications]=useState([]),[notificationsOpen,setNotificationsOpen]=useState(false),[incoming,setIncoming]=useState(null)
 const [loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[status,setStatus]=useState(''),[type,setType]=useState('')
 const canManage=['ADMIN','GESTOR'].includes(profile?.rol)
 async function load(){try{setLoading(true);const [r,w,n]=await Promise.all([getAllRequests(),getOliWorkers(),getNotifications()]);setRequests(r);setWorkers(w);setNotifications(n);setError('')}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{
  let active=true,previewTimer
  const refresh=()=>getNotifications().then(n=>{if(active)setNotifications(n)}).catch(e=>{if(active)setError(e.message)})
  Promise.all([getAllRequests(),getOliWorkers(),getNotifications()]).then(([r,w,n])=>{if(active){setRequests(r);setWorkers(w);setNotifications(n)}}).catch(e=>setError(e.message)).finally(()=>setLoading(false))
  const unsubscribe=subscribeToNotifications(payload=>{refresh();setIncoming(payload.new);clearTimeout(previewTimer);previewTimer=setTimeout(()=>setIncoming(null),8000)})
  const interval=setInterval(refresh,60000)
  return ()=>{active=false;clearInterval(interval);clearTimeout(previewTimer);unsubscribe()}
 },[])
 const filtered=useMemo(()=>requests.filter(r=>(!status||r.estado===status)&&(!type||r.tipo===type)&&(!query||`${r.codigo} ${r.nombre_solicitante} ${r.email_solicitante} ${r.asunto||''}`.toLowerCase().includes(query.toLowerCase()))),[requests,status,type,query])
 const counts=useMemo(()=>({total:requests.length,new:requests.filter(r=>r.estado==='RECIBIDA').length,review:requests.filter(r=>['EN_REVISION','OBSERVADA'].includes(r.estado)).length,approved:requests.filter(r=>r.estado==='APROBADA').length}),[requests])
 const unread=notifications.filter(item=>!item.leida_at).length
 const overdue=notifications.filter(item=>!item.leida_at&&isOverdue(item)).length
 async function open(id){try{setSelected(await getRequestDetails(id))}catch(e){setError(e.message)}}
 async function openNotification(item){try{if(!item.leida_at){await markNotificationRead(item.id);setNotifications(current=>current.map(n=>n.id===item.id?{...n,leida_at:new Date().toISOString()}:n))}setNotificationsOpen(false);setIncoming(null);if(item.solicitud_id)await open(item.solicitud_id)}catch(e){setError(e.message)}}
 async function mutate(action){try{await action();await load();if(selected)await open(selected.id)}catch(e){setError(e.message)}}
 async function logout(){await supabase.auth.signOut();navigate('/login')}
 return <main className="min-h-screen bg-slate-100"><header className="border-b bg-white px-4 py-4 sm:px-8"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4"><div><h1 className="text-2xl font-bold">Gestor OLI</h1><p className="text-sm text-slate-500">{profile?.nombre_completo} · {profile?.rol}</p></div><div className="flex flex-wrap items-center gap-2">{profile?.rol==='ADMIN'&&<Link to="/oli/voluntarios" className="rounded-lg border border-orange-200 bg-orange-50 px-4 py-2 text-sm font-bold text-orange-800 transition hover:bg-orange-100">Voluntarios</Link>}<Link to="/" className="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-bold text-white transition hover:bg-emerald-800">Ver sitio público</Link>{profile?.rol==='ADMIN'&&<Link to="/oli/perfiles" className="hidden rounded-lg border border-slate-200 px-4 py-2 text-sm font-bold text-slate-700 transition hover:bg-slate-50 sm:block">Configurar perfiles</Link>}<div className="relative"><button onClick={()=>setNotificationsOpen(value=>!value)} className={`relative grid h-11 w-11 place-items-center rounded-xl border transition hover:bg-slate-50 ${overdue?'border-red-300 bg-red-50 text-red-700':'border-slate-200 text-slate-700'}`} aria-label={`Notificaciones, ${unread} sin leer`} aria-expanded={notificationsOpen}><BellIcon/>{unread>0&&<span className="absolute -right-1.5 -top-1.5 min-w-5 rounded-full bg-red-600 px-1.5 py-0.5 text-center text-[11px] font-black text-white">{unread>99?'99+':unread}</span>}</button>{notificationsOpen&&<NotificationPanel notifications={notifications} onOpen={openNotification}/>}</div><button onClick={logout} className="rounded-lg border px-4 py-2">Cerrar sesión</button></div></div>{profile?.rol==='ADMIN'&&<Link to="/oli/perfiles" className="mx-auto mt-3 block max-w-7xl rounded-lg bg-slate-100 px-4 py-2 text-center text-sm font-bold text-slate-700 sm:hidden">Configurar perfiles</Link>}</header>
 <div className="mx-auto max-w-7xl p-4 sm:p-8">{/* Sección: resumen de indicadores de solicitudes. */}<section className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Total" value={counts.total}/><Stat label="Recibidas" value={counts.new}/><Stat label="En seguimiento" value={counts.review}/><Stat label="Aprobadas" value={counts.approved}/></section>
 {/* Sección: buscador y filtros de solicitudes. */}<section className="mt-6 grid gap-3 rounded-xl bg-white p-4 shadow-sm md:grid-cols-3"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar código, nombre o correo" className="rounded-lg border p-3"/><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg border p-3"><option value="">Todos los estados</option>{Object.keys(statusColor).map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select><select value={type} onChange={e=>setType(e.target.value)} className="rounded-lg border p-3"><option value="">Todos los tipos</option>{REQUEST_TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></section>
 {error&&<p className="mt-4 rounded-lg bg-red-100 p-3 text-red-800">{error}</p>}{/* Sección: listado de solicitudes filtradas. */}{loading?<p className="mt-8">Cargando solicitudes...</p>:<section className="mt-5 grid gap-3">{filtered.map(r=><button key={r.id} onClick={()=>open(r.id)} className="rounded-xl bg-white p-4 text-left shadow-sm transition hover:shadow"><div className="flex flex-wrap items-start justify-between gap-3"><div><span className="font-mono text-sm text-blue-700">{r.codigo}</span><h2 className="font-semibold">{r.asunto||labels[r.tipo]}</h2><p className="text-sm text-slate-500">{r.nombre_solicitante} · {r.email_solicitante}</p></div><div className="text-right"><StatusBadge status={r.estado}/><p className="mt-2 text-xs text-slate-400">{new Date(r.created_at).toLocaleString()}</p></div></div></button>)}{!filtered.length&&<p className="rounded-xl bg-white p-8 text-center text-slate-500">No se encontraron solicitudes.</p>}</section>}</div>
 {incoming&&<button onClick={()=>openNotification(incoming)} className="fixed right-4 top-20 z-50 w-[calc(100%-2rem)] max-w-sm rounded-2xl border border-emerald-200 bg-white p-4 text-left shadow-2xl"><div className="flex gap-3"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full bg-emerald-100 text-emerald-700"><BellIcon/></span><div><p className="text-xs font-black uppercase tracking-wider text-emerald-700">Nueva notificación</p><p className="mt-1 font-bold">{incoming.titulo}</p><p className="mt-1 line-clamp-2 text-sm text-slate-600">{incoming.mensaje}</p></div></div></button>}
 {selected&&<Detail request={selected} workers={workers} canManage={canManage} onClose={()=>setSelected(null)} onStatus={(s,n)=>s?mutate(()=>changeRequestStatus(selected.id,s,n)):open(selected.id).then(load)} onAssign={id=>mutate(()=>assignRequest(selected.id,id))} onPublish={contact=>mutate(()=>publishCollectionPoint(selected.id,contact))}/>}</main>
}

function NotificationPanel({notifications,onOpen}){/* Sección: panel desplegable de notificaciones y alertas pendientes. */return <section className="absolute right-0 top-14 z-40 w-[calc(100vw-2rem)] max-w-sm overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-2xl"><div className="flex items-center justify-between border-b px-4 py-3"><div><h2 className="font-bold">Notificaciones</h2><p className="text-xs text-slate-500">Actualizaciones de solicitudes</p></div><span className="rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold">{notifications.filter(n=>!n.leida_at).length} nuevas</span></div><div className="max-h-[28rem] overflow-y-auto">{notifications.length?notifications.map(item=>{const overdue=!item.leida_at&&isOverdue(item);return <button key={item.id} onClick={()=>onOpen(item)} className={`block w-full border-b px-4 py-4 text-left transition hover:bg-slate-50 ${!item.leida_at?'bg-blue-50/60':''}`}><div className="flex items-start gap-3"><span className={`mt-1 h-2.5 w-2.5 shrink-0 rounded-full ${overdue?'animate-pulse bg-red-500':item.leida_at?'bg-slate-200':'bg-blue-600'}`}/><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><p className="truncate text-sm font-bold">{item.titulo}</p>{overdue&&<span className="shrink-0 rounded-full bg-red-100 px-2 py-0.5 text-[10px] font-black text-red-700">Requiere atención</span>}</div><p className="mt-1 line-clamp-2 text-sm text-slate-600">{item.mensaje}</p>{item.solicitudes&&<p className="mt-2 truncate text-xs font-semibold text-blue-700">{item.solicitudes.codigo} · {item.solicitudes.nombre_solicitante}</p>}<p className="mt-1 text-xs text-slate-400">{timeAgo(item.created_at)}</p></div></div></button>}):<p className="p-8 text-center text-sm text-slate-500">No hay notificaciones.</p>}</div></section>}

function BellIcon(){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" className="h-5 w-5" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" d="M14.9 18a3 3 0 0 1-5.8 0m9.4-2.5H5.5c1.4-1.5 2-3.4 2-5.5a4.5 4.5 0 0 1 9 0c0 2.1.6 4 2 5.5Z"/></svg>}
function isOverdue(item){const date=item.solicitudes?.created_at||item.created_at;return Date.now()-new Date(date).getTime()>24*60*60*1000}
function timeAgo(value){const hours=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/3600000));if(hours<1)return 'Hace menos de una hora';if(hours<24)return `Hace ${hours} h`;const days=Math.floor(hours/24);return `Hace ${days} ${days===1?'día':'días'}`}

function Stat({label,value}){return <div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>}

function Detail({request,workers,canManage,onClose,onStatus,onAssign,onPublish}){
 const [next,setNext]=useState(''),[note,setNote]=useState(''),[contact,setContact]=useState('')
 const detail=request[relations[request.tipo]], transitions=ALLOWED_TRANSITIONS[request.estado]||[]
 return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/50 p-3 sm:p-8"><article className="ml-auto min-h-full max-w-3xl rounded-2xl bg-white p-5 shadow-xl sm:p-8"><div className="flex justify-between gap-4"><div><span className="font-mono text-blue-700">{request.codigo}</span><h2 className="text-2xl font-bold">{labels[request.tipo]}</h2><div className="mt-2"><StatusBadge status={request.estado}/></div></div><button onClick={onClose} className="h-10 rounded-lg border px-4">Cerrar</button></div>
 <Section title="Solicitante"><Data label="Nombre" value={request.nombre_solicitante}/><Data label="Correo" value={request.email_solicitante}/><Data label="Teléfono" value={request.telefono_solicitante}/></Section>
 <Section title="Solicitud"><Data label="Asunto" value={request.asunto}/><Data label="Descripción" value={request.descripcion}/><Data label="Prioridad" value={request.prioridad}/><Data label="Ubicación" value={[request.direccion,request.distrito,request.provincia,request.region].filter(Boolean).join(', ')}/>{request.latitud!=null&&<a target="_blank" rel="noreferrer" className="text-blue-700 underline" href={`https://www.openstreetmap.org/?mlat=${request.latitud}&mlon=${request.longitud}#map=17/${request.latitud}/${request.longitud}`}>Abrir ubicación en el mapa</a>}</Section>
 {detail&&<Section title="Información específica">{Object.entries(detail).filter(([k,v])=>!['solicitud_id','created_at'].includes(k)&&v!==null&&v!=='').map(([k,v])=><Data key={k} label={k.replaceAll('_',' ')} value={String(v)}/>)}</Section>}
 <Section title="Evidencias">{request.evidencias?.length?request.evidencias.map(e=><a key={e.id} href={e.url||'#'} target="_blank" rel="noreferrer" className="block text-blue-700 underline">{e.nombre_original}</a>):<p className="text-slate-500">Sin evidencias</p>}</Section>
 <Section title="Historial"><ol className="space-y-2">{[...(request.solicitud_historial||[])].sort((a,b)=>new Date(b.created_at)-new Date(a.created_at)).map(h=><li key={h.id} className="border-l-2 pl-3"><b>{statusLabels[h.estado_nuevo]||h.estado_nuevo}</b><p className="text-sm text-slate-500">{new Date(h.created_at).toLocaleString()} {h.observacion&&`· ${h.observacion}`}</p></li>)}</ol></Section>
 {canManage&&<Section title="Gestión"><label className="block text-sm font-medium">Responsable<select value={request.asignado_a||''} onChange={e=>onAssign(e.target.value)} className="mt-1 w-full rounded-lg border p-3"><option value="">Sin asignar</option>{workers.map(w=><option key={w.id} value={w.id}>{w.nombre_completo} · {w.rol}</option>)}</select></label>{transitions.length>0&&<div className="mt-4 grid gap-3"><select value={next} onChange={e=>setNext(e.target.value)} className="rounded-lg border p-3"><option value="">Selecciona el nuevo estado</option>{transitions.map(s=><option key={s} value={s}>{statusLabels[s]}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Observación para el historial y correo" className="rounded-lg border p-3"/>{request.tipo==='EMERGENCIA'&&next==='APROBADA'?<EmergencyPhotoApproval key={request.id} request={request} approve observation={note} onSaved={()=>onStatus(null)}/>:<button disabled={!next} onClick={()=>onStatus(next,note)} className="rounded-lg bg-blue-700 p-3 font-semibold text-white disabled:opacity-50">Actualizar estado</button>}</div>}{request.tipo==='EMERGENCIA'&&request.estado==='APROBADA'&&<EmergencyPhotoApproval key={request.id} request={request} onSaved={()=>onStatus(null)}/>}{request.tipo==='PUNTO_ACOPIO'&&['APROBADA','ATENDIDA'].includes(request.estado)&&<div className="mt-5 border-t pt-5"><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Contacto público opcional" className="w-full rounded-lg border p-3"/><button onClick={()=>onPublish(contact)} className="mt-2 rounded-lg bg-emerald-700 px-4 py-3 font-semibold text-white">Publicar punto de acopio</button></div>}</Section>}
 </article></div>
}
function Section({title,children}){/* Sección: agrupación reutilizable de datos del detalle de una solicitud. */return <section className="mt-6 border-t pt-5"><h3 className="mb-3 text-lg font-semibold">{title}</h3><div className="grid gap-3 sm:grid-cols-2">{children}</div></section>} 
function Data({label,value}){if(value===null||value===undefined||value==='')return null;return <div><dt className="text-xs font-semibold uppercase text-slate-400">{label}</dt><dd className="whitespace-pre-wrap text-sm">{value}</dd></div>}
function StatusBadge({status}){return <span className={`inline-flex items-center rounded-full px-3 py-1 text-xs font-semibold ${statusColor[status]||'bg-slate-100 text-slate-700'}`}>{statusLabels[status]||status}</span>}
export default Dashboard
